# Checks WordPress git tag and commits if changed

name: WordPress version

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    # * is a special character in YAML so you have to quote this string.
    # /30 denotes that it will run once every 30 minutes
    - cron:  '*/15 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "wpv"
  wpv:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.WPV_REPO_TOKEN }}
    # Get WordPress version
    - name: Get WordPress version
      run: |
        export wpversion=$(git ls-remote --tags https://github.com/WordPress/WordPress.git | tail -n1 | awk -F'/' '{print $3}')
        if [ -n "$wpversion" ]; then
          export fileversion=$(cat index.html)
          if [ $fileversion != $wpversion ];
          then
                echo $wpversion > index.html
                git config --local user.email "builder@github.example"
                git config --local user.name "GitHub's Little Builder"
                git add .
                git commit -m "$wpversion, checked: $(date +'%F %T %Z')"
                git push origin master
          else
            exit 0;
          fi
        fi
